# Site settings
owner: mahesh narayanamurthi
title: byteswap
tagline: irrational numbers amuse me.
email: mytwitterhandle@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  everything about computers, maths and science. occasional ramblings included.

# Social settings
twitter_username: maheshnmurthi
github_username:  mod0

# Build settings
markdown: kramdown

# Timezone settings
timezone: America/New_York

# Defaults

